name: smart_pantry
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.1.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  uuid: ^4.5.2
  google_fonts: ^8.0.1
  firebase_core: ^4.4.0

  firebase_auth: ^6.1.4
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6     # <-- เพิ่มเพื่อรองรับ Image Upload
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true


